# 변수 설정
@queueToken = {{queueToken}}
@concertId = {{concertId}}
@seatId = {{seatId}}

### 예약
POST {{host}}/api/v1/reservations
Content-Type: application/json
QUEUE_TOKEN: {{queueToken}}

{
  "concertId": "{{concertId}}",
  "userId": "{{userId}}",
  "seatId": "{{seatId}}"
}

> {%
    client.global.set("reservationId", response.body.data.id)
%}

### 예약 결제
POST {{host}}/api/v1/reservations/pay
Content-Type: application/json
QUEUE_TOKEN: {{queueToken}}

{
  "reservationId": "{{reservationId}}",
  "token": "{{queueToken}}"
}