
global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mysql"
    static_configs:
      - targets: ["host.docker.internal:9104"]

  - job_name: "redis"
    static_configs:
      - targets: ["host.docker.internal:9121"]

  - job_name: "application"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8080"]
